version: "3.9"

x-logging: &v_logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "4"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - v_bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/martokk/FILES/Servers/martokk/volumes/portainer:/data
    ports:
      - 9000:9000

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    privileged: true
    restart: unless-stopped
    networks:
      - v_bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/martokk/FILES/Servers/martokk/volumes/webtop-vdev:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    shm_size: "2gb"
    security_opt:
      - seccomp:unconfined

  #code-server:
  #image: linuxserver/code-server:4.7.1
  #container_name: code-server
  #restart: unless-stopped
  #networks:
  #- v_bridge
  #environment:
  #- TZ=America/Chicago # Specify a timezone to use EG Europe/London
  #- PUID=1000 # for UserID
  #- PGID=1000 # for GroupID
  #volumes:
  #- /media/martokk/FILES/Servers/martokk/volumes/code-server:/config
  #- local_projects:/Projects
  #ports:
  #- 8443:8443/tcp # Web UI

# TOP-LEVEL CONFIG
networks:
  v_bridge:
    driver: bridge

volumes:
  # FILES - Internal HDD Partition
  local_projects:
    driver_opts:
      device: "/media/martokk/FILES/Projects"
      o: bind
      type: none

  # WD_2TB - External HDD - Western Digital 2TB

  # WD_4TB - External HDD - Western Digital 4TB[
